### ISSUE TITLE
Database missing

### ISSUE THREAD

**Issue by gabriel-lucas** [fandu/MetroViz#14]
I tried to download the database from https://www.dropbox.com/s/pdmp0bhtswtcg7x/Metroviz.zip , but it does not work. Could you re-upload it to a persistent location?

thanks

**Comment by fandu** [comment]
Thanks for catching this. Link updated.
https://1drv.ms/u/s!Ag49pvBmXMrfgrVY66y5fX4qkd7yjQ

**Comment by gabriel-lucas** [comment]
Thanks, that was fast! 👍

**Comment by fandu** [comment]
Leave us a star if this project is helpful : )
